---
driver:
  name: vagrant

provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec
#   format: doc

platforms:
  - name: solaris-11
    driver:
      box: 'chef/solaris-11.3'
      network:
        - ["public_network", {bridge: "en0: Wi-Fi (AirPort)"}]
#      box_url: '/Users/shain/oc/code/opscode/bento/builds/solaris-11.3.virtualbox.box'


suites:
  - name: default
    run_list:
      - recipe[zone::default]
    attributes:
