name 'zone'
maintainer 'Scott Hain <shain@chef.io>'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures zone'
long_description 'Installs/Configures zone'
version '0.1.0'
